### ISSUE TITLE
merged word for millions amount-

### ISSUE THREAD

**Issue by kishoreaoe** [omar-ehab/tafgeet-js#1]
dear Omar,

we are trying this amount, and as per our testing team the amount is reading as incorrect in arabic. can you please help on this.

this.amount= new Tafgeet(2250000.00, 'QAR').parse();

amount:- 2,250,000.00
amount in arabic:- مليونينمائتين وخمسون ألف ريال قطري فقط لا غير

As per our guys, the first words are getting as merged, and correct representation would be like:- 

مليونين و مائتين  

your support would be highly helpful for our scenario.

**Comment by omar-ehab** [comment]
Dear @kishoreaoe 

Thank you for utilizing the package and bringing the issue to our attention.

I'm happy to let you know that the issue has been resolved in the latest patch, version 1.0.11. We recommend updating the package to the most recent version to benefit from the fix.

Thank you for your understanding.

**Comment by kishoreaoe** [comment]
Dear @omar-ehab  thanks alot for the quick support on this, we used the newly provided fix, however as per our testing guys, they are said "still one letter is missing between two words". can you please kindly help on this.

PFB image:-
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
![test_tafgeet](https://github.com/omar-ehab/tafgeet-arabic/assets/6896519/5d70c50a-3420-420e-88b8-3a81f5e4140c)
