### ISSUE TITLE
intuitive way to convert to number only (without currency)

### ISSUE THREAD

**Issue by thenbe** [omar-ehab/tafgeet-js#6]
There is a more intuitive way to omit the currency from the result, but that involves removing `EGP` as the default currency.

```typescript
// current
new Tafgeet('1').parse()        // واحد جنيه مصري فقط لا غير
new Tafgeet('1', '').parse()    // واحد فقط لا غير
new Tafgeet('1', 'EGP').parse() // واحد جنيه مصري فقط لا غير

// proposed
new Tafgeet('1').parse()        // واحد فقط لا غير
new Tafgeet('1', '').parse()    // واحد فقط لا غير
new Tafgeet('1', 'EGP').parse() // واحد جنيه مصري فقط لا غير
```

This would be a breaking change, so it might be worthwhile to increment the major version to (v2.0.0) to notify existing users.

Later, if this is implemented, we can look to validate the currency name passed in by the user and error if it is incorrect. This can also help tighten the types a bit when parsing by removing some of the [typecasting](https://github.com/omar-ehab/tafgeet-arabic/blob/cafa15772048041983f35f8e4d74093bf0d38531/src/index.ts#L97C59-L97C85).

---

P.S. I don't want to step on any toes. So if you intend to use this library mostly where `EGP` is needed, and would therefore like to keep `EGP` as default, that's perfectly fine. I guess what I'm asking is: would you like to see this repo become a maintained fork of https://github.com/mmahgoub/tafgeetjs, or would you prefer tailoring it to a more personal use case?

Since https://github.com/mmahgoub/tafgeetjs is currently unmaintained with 5 outstanding PR's, I personally think a community maintained fork needs to exist *somewhere*. Given that you've already done the legwork of adding typescript and tests, I *think* this is what your intention is here? Instead of assuming however, I thought it best to ask.

**Comment by omar-ehab** [comment]
Actually, I like to Omit the currency and make it optional

My vision for the package is to enhance and make it more reliable

the enhancement includes grammars because it's not that good right now

**Comment by thenbe** [comment]
Fair enough
